name: Create badges

on:
    release:
        types: [published]
    workflow_dispatch:
    push:

jobs:
    badges:
        name: Create badges
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@2.9.0
              with:
                  php-version: '8.1'
                  extensions: simplexml, dom, xml, xdebug, intl
                  tools: composer:v2
              env:
                  COMPOSER_TOKEN: ${{ secrets.YARD_BOT_PAT }}

            - name: Install dependencies
              run: composer install --prefer-dist

            - name: Recreate autoload file
              run: composer dump-autoload

            - name: Run Unit Tests
              run: XDEBUG_MODE_COVERAGE=coverage vendor/bin/pest --coverage-clover=clover.xml

            - name: Make lines of code badge
              uses: DeathSy/GHA-LoC-Badge@1.0.3
              id: badge
              with:
                  debug: true
                  directory: ./src
                  patterns: '**/*.php'
                  badge: ./output/lines-of-code.svg

            - name: Make code coverage badge
              uses: timkrase/phpunit-coverage-badge@v1.2.1
              with:
                  coverage_badge_path: output/coverage.svg
                  push_badge: false

            - name: Git push to badges branch
              uses: peaceiris/actions-gh-pages@v4
              with:
                  publish_dir: ./output
                  publish_branch: badges
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'
